name: Setup
description: Configures Node.js and installs dependencies
inputs:
  node-version:
    description: Version of Node.js to configure
    required: true
runs:
  using: "composite"
  steps:
    -   name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          check-latest: true
          node-version: ${{ inputs.node-version }}
    -   name: Install dependencies
        run: |
          npm install -g npm-cli-login
          npm config set registry $NPM_REGISTRY/
          npm-cli-login -e $NPM_EMAIL -p $NPM_PASSWORD -r $NPM_REGISTRY -u $NPM_EMAIL
          npm ci
