name: Setup
description: Configures Node.js and installs dependencies
inputs:
  node-version:
    description: Version of Node.js to configure
    required: true
runs:
  using: "composite"
  steps:
    -   name: Setup Node
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        with:
          cache: npm
          check-latest: true
          node-version: ${{ inputs.node-version }}
          always-auth: true
          registry-url: ${{secrets.NPM_REGISTRY}}
    -   name: Install dependencies
        shell: bash
        run: |
          npm install -g npm-cli-login
          npm config set registry $NPM_REGISTRY/
          npm-cli-login -e $NPM_EMAIL -p $NPM_PASSWORD -r $NPM_REGISTRY -u $NPM_EMAIL
          npm ci
