name: Setup
description: Configures Node.js and installs dependencies
inputs:
  node-version:
    description: Version of Node.js to configure
    required: true
runs:
  using: "composite"
  steps:
    -   name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          check-latest: true
          node-version: 16.13.2
          registry-url: https://metoffice.jfrog.io/metoffice/api/npm/npm

