/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ImpactMatrix {
        /**
          * the impact of the warning 1-4
         */
        "impact": number;
        /**
          * the likelihood of the warning 1-4
         */
        "likelihood": number;
    }
}
declare global {
    interface HTMLImpactMatrixElement extends Components.ImpactMatrix, HTMLStencilElement {
    }
    var HTMLImpactMatrixElement: {
        prototype: HTMLImpactMatrixElement;
        new (): HTMLImpactMatrixElement;
    };
    interface HTMLElementTagNameMap {
        "impact-matrix": HTMLImpactMatrixElement;
    }
}
declare namespace LocalJSX {
    interface ImpactMatrix {
        /**
          * the impact of the warning 1-4
         */
        "impact"?: number;
        /**
          * the likelihood of the warning 1-4
         */
        "likelihood"?: number;
    }
    interface IntrinsicElements {
        "impact-matrix": ImpactMatrix;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "impact-matrix": LocalJSX.ImpactMatrix & JSXBase.HTMLAttributes<HTMLImpactMatrixElement>;
        }
    }
}
